# Generated by Django 6.0.5 on 2026-07-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PermissoesPcp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("pode_visualizar_calendario_ops", "Pode visualizar Calendário de OPs")
                ],
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
