# Generated by Django 6.0.5 on 2026-06-30 21:27

import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Calendario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("descricao", models.CharField(max_length=100, verbose_name="Descrição")),
            ],
            options={
                "verbose_name": "Calendário",
                "verbose_name_plural": "Calendários",
                "db_table": "calendario",
                "ordering": ["descricao"],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="CentroRecurso",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("codigo", models.CharField(max_length=50, verbose_name="Código")),
                ("descricao", models.CharField(max_length=255, verbose_name="Descrição")),
                (
                    "codigo_integrador",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Código Integrador"
                    ),
                ),
            ],
            options={
                "verbose_name": "Centro de Recurso",
                "verbose_name_plural": "Centros de Recursos",
                "db_table": "centros_recursos",
                "ordering": ["descricao"],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Empresa",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("codemp", models.IntegerField(unique=True, verbose_name="Código da Empresa")),
                ("nome", models.CharField(max_length=255, verbose_name="Nome")),
                ("fantasia", models.CharField(max_length=255, verbose_name="Nome Fantasia")),
                (
                    "loteatual",
                    models.CharField(default="100000000", max_length=50, verbose_name="Lote Atual"),
                ),
                ("ativa", models.BooleanField(default=True, verbose_name="Ativa")),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
                "db_table": "empresas",
                "ordering": ["nome"],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Tara",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("tara", models.CharField(max_length=100, verbose_name="Tara")),
                (
                    "peso",
                    models.DecimalField(decimal_places=3, max_digits=10, verbose_name="Peso (kg)"),
                ),
            ],
            options={
                "verbose_name": "Tara",
                "verbose_name_plural": "Taras",
                "db_table": "taras",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="CalendarioEvento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("data", models.DateField(verbose_name="Data")),
                (
                    "motivo",
                    models.SmallIntegerField(
                        choices=[(1, "Dia Não Produtivo"), (2, "Feriado"), (3, "Manutenção")],
                        verbose_name="Motivo",
                    ),
                ),
                (
                    "observacao",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Observação"
                    ),
                ),
                (
                    "calendario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos",
                        to="accounts.calendario",
                        verbose_name="Calendário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento de Calendário",
                "verbose_name_plural": "Eventos de Calendário",
                "db_table": "calendario_eventos",
                "ordering": ["data"],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Filial",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("codfil", models.IntegerField(verbose_name="Código da Filial")),
                ("nome", models.CharField(max_length=255, verbose_name="Nome")),
                ("fantasia", models.CharField(max_length=255, verbose_name="Nome Fantasia")),
                ("cnpj", models.CharField(max_length=18, verbose_name="CNPJ")),
                ("ativa", models.BooleanField(default=True, verbose_name="Ativa")),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="filiais",
                        to="accounts.empresa",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Filial",
                "verbose_name_plural": "Filiais",
                "db_table": "filial",
                "ordering": ["nome"],
                "default_permissions": (),
                "unique_together": {("empresa", "codfil")},
            },
        ),
        migrations.CreateModel(
            name="Departamento",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("descricao", models.CharField(max_length=255, verbose_name="Descrição")),
                (
                    "filial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.filial",
                        verbose_name="Filial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Departamento",
                "verbose_name_plural": "Departamentos",
                "db_table": "departamentos",
                "ordering": ["descricao"],
                "default_permissions": (),
            },
        ),
        migrations.AddField(
            model_name="calendario",
            name="filial",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="calendarios",
                to="accounts.filial",
                verbose_name="Filial",
            ),
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={"unique": "A user with that username already exists."},
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=150, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=150, verbose_name="last name"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email address"),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("idintegracao", models.IntegerField(blank=True, null=True)),
                (
                    "idoperador",
                    models.IntegerField(blank=True, null=True, verbose_name="ID Operador"),
                ),
                ("paginicial", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "filial",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.filial",
                    ),
                ),
            ],
            options={
                "db_table": "accounts_customuser",
                "default_permissions": (),
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="ParametrosCentroRecurso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "deposito_apontamento_erp",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Depósito de consulta apontamento ERP",
                    ),
                ),
                (
                    "deposito_armazenamento_erp",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Depósito de armazenamento ERP",
                    ),
                ),
                (
                    "deposito_armazenamento_wms",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Local de liberação WMS"
                    ),
                ),
                (
                    "deposito_area_vermelha_erp",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Depósito área vermelha ERP",
                    ),
                ),
                (
                    "deposito_area_vermelha_wms",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Local área vermelha WMS"
                    ),
                ),
                (
                    "produto_refugo",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Produto refugo"
                    ),
                ),
                (
                    "derivacao_refugo",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Derivação refugo"
                    ),
                ),
                (
                    "cod_alchemy",
                    models.IntegerField(blank=True, null=True, verbose_name="Cód. Alchemy"),
                ),
                (
                    "centro_recurso",
                    models.OneToOneField(
                        db_column="centros_recursos_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parametros_centro_recurso",
                        to="accounts.centrorecurso",
                        verbose_name="Centro de Recurso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parâmetros do Centro de Recurso",
                "verbose_name_plural": "Parâmetros dos Centros de Recursos",
                "db_table": "parametros_centros_recursos",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="ParametrosFilial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tempo_sem_comunicacao_manual",
                    models.PositiveIntegerField(
                        default=15,
                        verbose_name="Tempo sem comunicação para apontar manualmente (segundos)",
                    ),
                ),
                (
                    "limite_apontamento_minimo",
                    models.FloatField(default=0, verbose_name="Limite mínimo de apontamento"),
                ),
                (
                    "limite_apontamento_maximo",
                    models.FloatField(default=4000, verbose_name="Limite máximo de apontamento"),
                ),
                (
                    "codtns",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Transação de ERP Saída por Transferência Interna",
                    ),
                ),
                (
                    "codtns_area_vermelha",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Transação do ERP Saída Área Vermelha",
                    ),
                ),
                (
                    "deposito_apontamento_erp",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Depósito de consulta apontamento ERP",
                    ),
                ),
                (
                    "deposito_armazenamento_erp",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Depósito de armazenamento ERP",
                    ),
                ),
                (
                    "deposito_armazenamento_wms",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="Local de liberação WMS"
                    ),
                ),
                (
                    "deposito_area_vermelha_erp",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Depósito área vermelha ERP",
                    ),
                ),
                (
                    "deposito_area_vermelha_wms",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Local área vermelha WMS",
                    ),
                ),
                (
                    "produto_refugo",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="Produto refugo"
                    ),
                ),
                (
                    "derivacao_refugo",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="Derivação refugo"
                    ),
                ),
                (
                    "origens_area_vermelha",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Origens área vermelha"
                    ),
                ),
                (
                    "transacoes_saida_consumo_producao",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Transações de saída para consumo na produção",
                    ),
                ),
                (
                    "transacoes_entrada_producao_consumo",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Transações de entrada por Produção",
                    ),
                ),
                (
                    "filial",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parametros_filial",
                        to="accounts.filial",
                        verbose_name="Filial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parâmetros da Filial",
                "verbose_name_plural": "Parâmetros das Filiais",
                "db_table": "parametros_filial",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Recurso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("codigo", models.CharField(max_length=50)),
                ("descricao", models.CharField(max_length=200)),
                ("habilita_oee", models.BooleanField(default=False)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "ordenacao",
                    models.IntegerField(blank=True, null=True, verbose_name="Ordenação Visual"),
                ),
                (
                    "ordenacao_sequenciamento",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Ordenação Sequenciamento"
                    ),
                ),
                (
                    "modelo_prd",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Unitário"),
                            (2, "Lote"),
                            (3, "Batelada"),
                            (4, "Contínuo"),
                            (5, "Serviço"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "opers_simut",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[(1, "Única"), (2, "Múltipla"), (3, "Simultânea")],
                        null=True,
                    ),
                ),
                (
                    "tipo_parada",
                    models.SmallIntegerField(
                        blank=True, choices=[(1, "Manual"), (2, "Sinal")], null=True
                    ),
                ),
                ("tempo_parada_aut", models.DurationField(blank=True, null=True)),
                ("metadis", models.FloatField(blank=True, null=True)),
                ("metaper", models.FloatField(blank=True, null=True)),
                ("metaqual", models.FloatField(blank=True, null=True)),
                ("metaooee", models.FloatField(blank=True, null=True)),
                ("view_id", models.IntegerField(blank=True, null=True, verbose_name="View")),
                ("quant_pes", models.IntegerField(blank=True, null=True)),
                ("exibir_jus", models.BooleanField(blank=True, null=True)),
                (
                    "alt_just",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Bloqueado"),
                            (2, "Apenas Sem Justificativa"),
                            (3, "Liberado"),
                            (4, "Última Parada"),
                            (5, "Apenas Turno Atual"),
                        ],
                        null=True,
                    ),
                ),
                ("inic_parada_prog", models.BooleanField(blank=True, null=True)),
                ("fin_parada_prog", models.BooleanField(blank=True, null=True)),
                (
                    "alt_parada_prog",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Bloqueado"),
                            (2, "Liberado"),
                            (3, "Apenas Redução"),
                            (4, "Apenas Acréscimo"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "mod_he",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[(1, "Automática"), (2, "Manual"), (3, "Operação Aberta")],
                        null=True,
                    ),
                ),
                (
                    "desvio_pro",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[(1, "Bloquear"), (2, "Permitir"), (3, "Solicitar Justificativa")],
                        null=True,
                    ),
                ),
                (
                    "bobina",
                    models.IntegerField(
                        blank=True, editable=False, null=True, verbose_name="Bobina"
                    ),
                ),
                (
                    "centro_recurso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recursos",
                        to="accounts.centrorecurso",
                    ),
                ),
            ],
            options={
                "db_table": "recursos",
                "ordering": ["ordenacao", "descricao"],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="ParametrosRecurso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tempo_sem_comunicacao_manual",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Tempo sem comunicação para apontar manualmente (segundos)",
                    ),
                ),
                (
                    "limite_apontamento_minimo",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Limite mínimo de apontamento"
                    ),
                ),
                (
                    "limite_apontamento_maximo",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Limite máximo de apontamento"
                    ),
                ),
                ("aponta_refugo", models.BooleanField(default=True, verbose_name="Aponta Refugo")),
                (
                    "recurso",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parametros_recurso",
                        to="accounts.recurso",
                        verbose_name="Recurso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parâmetros do Recurso",
                "verbose_name_plural": "Parâmetros dos Recursos",
                "db_table": "parametros_recursos",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="LogTrocaOPAtiva",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "codigo_barra_op",
                    models.CharField(max_length=100, verbose_name="Código de Barras da OP"),
                ),
                ("horario_troca", models.DateTimeField(verbose_name="Horário da Troca")),
                (
                    "horario_saida",
                    models.DateTimeField(blank=True, null=True, verbose_name="Horário de Saída"),
                ),
                (
                    "id_operador",
                    models.IntegerField(blank=True, null=True, verbose_name="ID Operador"),
                ),
                (
                    "recurso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="logs_troca_op_ativa",
                        to="accounts.recurso",
                        verbose_name="Recurso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Troca de OP Ativa",
                "verbose_name_plural": "Logs de Troca de OP Ativa",
                "db_table": "logs_troca_op_ativa",
                "ordering": ["-horario_troca"],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Setor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("descricao", models.CharField(max_length=255, verbose_name="Descrição")),
                (
                    "departamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.departamento",
                        verbose_name="Departamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Setor",
                "verbose_name_plural": "Setores",
                "db_table": "setores",
                "ordering": ["descricao"],
                "default_permissions": (),
            },
        ),
        migrations.AddField(
            model_name="centrorecurso",
            name="setor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.setor",
                verbose_name="Setor",
            ),
        ),
        migrations.CreateModel(
            name="TurnoBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("codigo", models.CharField(max_length=20, unique=True, verbose_name="Código")),
                ("descricao", models.CharField(max_length=255, verbose_name="Descrição")),
                ("ordenacao", models.IntegerField(verbose_name="Ordenação")),
                (
                    "calendario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.calendario",
                        verbose_name="Calendário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Turno Base",
                "verbose_name_plural": "Turnos Base",
                "db_table": "turnos_base",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="HoraExtraPlanejada",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "dias",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(
                            choices=[
                                (1, "Segunda"),
                                (2, "Terça"),
                                (3, "Quarta"),
                                (4, "Quinta"),
                                (5, "Sexta"),
                                (6, "Sábado"),
                                (7, "Domingo"),
                            ]
                        ),
                        blank=True,
                        null=True,
                        verbose_name="Dias da Semana",
                    ),
                ),
                ("data_inicio", models.DateField(verbose_name="Data Início")),
                ("data_fim", models.DateField(verbose_name="Data Fim")),
                ("hora_inicio", models.TimeField(verbose_name="Hora Início")),
                ("hora_fim", models.TimeField(verbose_name="Hora Fim")),
                (
                    "considera_feriado",
                    models.BooleanField(default=False, verbose_name="Considera Feriado"),
                ),
                (
                    "recurso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.recurso",
                        verbose_name="Recurso",
                    ),
                ),
                (
                    "turnobase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accounts.turnobase",
                        verbose_name="Turno Base",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hora Extra Planejada",
                "verbose_name_plural": "Horas Extras Planejadas",
                "db_table": "horas_extras_planejadas",
                "ordering": ["data_inicio", "hora_inicio"],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="TurnoRecurso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "dias",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(
                            choices=[
                                (1, "Segunda"),
                                (2, "Terça"),
                                (3, "Quarta"),
                                (4, "Quinta"),
                                (5, "Sexta"),
                                (6, "Sábado"),
                                (7, "Domingo"),
                            ]
                        )
                    ),
                ),
                ("hora_inicio", models.TimeField()),
                ("hora_fim", models.TimeField()),
                (
                    "recurso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="accounts.recurso"
                    ),
                ),
                (
                    "turnobase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="accounts.turnobase"
                    ),
                ),
            ],
            options={
                "verbose_name": "Turno de Recurso",
                "verbose_name_plural": "Turnos de Recursos",
                "db_table": "turnos_recursos",
                "ordering": ["recurso", "hora_inicio"],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="OEEPlanejadoDiario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("data", models.DateField()),
                ("minutos_planejados", models.IntegerField()),
                (
                    "recurso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.recurso"
                    ),
                ),
            ],
            options={
                "db_table": 'public"."oee_planejado_diario',
                "default_permissions": (),
                "indexes": [models.Index(fields=["data"], name="oee_planeja_data_30140b_idx")],
                "unique_together": {("recurso", "data")},
            },
        ),
        migrations.CreateModel(
            name="LeituraMQTT",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField()),
                ("balanca", models.FloatField(blank=True, null=True)),
                (
                    "estado",
                    models.IntegerField(
                        blank=True, choices=[(1, "Produzindo"), (0, "Parado")], null=True
                    ),
                ),
                (
                    "recurso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leituras_mqtt",
                        to="accounts.recurso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leitura MQTT",
                "verbose_name_plural": "Leituras MQTT",
                "db_table": 'public"."leituras_mqtt',
                "ordering": ["-timestamp"],
                "default_permissions": (),
                "indexes": [
                    models.Index(
                        fields=["recurso", "-timestamp"], name="idx_leitura_recurso_ts_desc"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EstadoRecurso",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("inicio", models.DateTimeField()),
                ("fim", models.DateTimeField(blank=True, null=True)),
                ("estado", models.IntegerField(choices=[(1, "Produzindo"), (0, "Parado")])),
                (
                    "recurso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estados",
                        to="accounts.recurso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estado do Recurso",
                "verbose_name_plural": "Estados dos Recursos",
                "db_table": 'public"."estados_recursos',
                "ordering": ["-inicio"],
                "default_permissions": (),
                "indexes": [
                    models.Index(fields=["estado", "fim"], name="idx_estado_fim"),
                    models.Index(fields=["recurso", "fim"], name="idx_recurso_fim"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RecursoTara",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "recurso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurso_taras",
                        to="accounts.recurso",
                    ),
                ),
                (
                    "tara",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tara_recursos",
                        to="accounts.tara",
                    ),
                ),
            ],
            options={
                "verbose_name": "Relacionamento Recurso Tara",
                "verbose_name_plural": "Relacionamentos Recurso Tara",
                "db_table": "recurso_taras",
                "default_permissions": (),
                "unique_together": {("recurso", "tara")},
            },
        ),
    ]
