# Generated by Django 6.0.5 on 2026-07-10 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParadaMaquina",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("inicio", models.DateTimeField(verbose_name="Data/Hora Início")),
                ("fim", models.DateTimeField(blank=True, null=True, verbose_name="Data/Hora Fim")),
                ("op_ativa", models.CharField(blank=True, max_length=100, verbose_name="OP Ativa")),
                (
                    "operador_atual",
                    models.CharField(blank=True, max_length=100, verbose_name="Operador Atual"),
                ),
                ("motivo", models.CharField(blank=True, max_length=255, verbose_name="Motivo")),
                (
                    "motivo_registrado_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data/Hora Registro do Motivo"
                    ),
                ),
                (
                    "tipo",
                    models.SmallIntegerField(
                        choices=[(1, "Manual"), (2, "Sinal")], verbose_name="Tipo"
                    ),
                ),
            ],
            options={
                "verbose_name": "Parada de Máquina",
                "verbose_name_plural": "Paradas de Máquina",
                "db_table": 'producao"."paradas_maquina',
                "ordering": ["-inicio"],
                "default_permissions": (),
            },
        ),
        migrations.RemoveIndex(
            model_name="estadorecurso",
            name="idx_estado_fim",
        ),
        migrations.RemoveIndex(
            model_name="estadorecurso",
            name="idx_recurso_fim",
        ),
        migrations.RemoveIndex(
            model_name="leituramqtt",
            name="idx_leitura_recurso_ts_desc",
        ),
        migrations.AddField(
            model_name="paradamaquina",
            name="recurso",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paradas_maquina",
                to="accounts.recurso",
            ),
        ),
        migrations.AddField(
            model_name="paradamaquina",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="paradas_maquina_registradas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.RemoveField(
            model_name="estadorecurso",
            name="recurso",
        ),
        migrations.RemoveField(
            model_name="leituramqtt",
            name="recurso",
        ),
        migrations.AddIndex(
            model_name="paradamaquina",
            index=models.Index(fields=["recurso", "fim"], name="idx_parada_recurso_fim"),
        ),
        migrations.AddIndex(
            model_name="paradamaquina",
            index=models.Index(fields=["tipo", "fim"], name="idx_parada_tipo_fim"),
        ),
        migrations.AddConstraint(
            model_name="paradamaquina",
            constraint=models.UniqueConstraint(
                condition=models.Q(("fim__isnull", True)),
                fields=("recurso",),
                name="uniq_parada_aberta_recurso",
            ),
        ),
        migrations.DeleteModel(
            name="EstadoRecurso",
        ),
        migrations.DeleteModel(
            name="LeituraMQTT",
        ),
    ]
