# Generated by Django 6.0.5 on 2026-07-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_rename_campos_paradamaquina"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurso",
            name="aponta_parada",
            field=models.BooleanField(default=False, verbose_name="Aponta Parada"),
        ),
    ]
