# Generated by Django 6.0.5 on 2026-07-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_copia_exibir_jus_para_aponta_parada"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recurso",
            name="exibir_jus",
            field=models.BooleanField(default=False, verbose_name="Exibir Justificativas"),
        ),
    ]
