# Generated by Django 6.0.5 on 2026-07-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_recurso_exibir_jus"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recurso",
            name="desvio_pro",
        ),
        migrations.RemoveField(
            model_name="recurso",
            name="tipo_parada",
        ),
        migrations.AddField(
            model_name="recurso",
            name="permite_parada_manual",
            field=models.BooleanField(default=False, verbose_name="Permite Parada Manual"),
        ),
        migrations.AlterField(
            model_name="recurso",
            name="alt_just",
            field=models.SmallIntegerField(
                blank=True,
                choices=[
                    (1, "Bloqueado"),
                    (2, "Apenas Sem Justificativa"),
                    (3, "Liberado"),
                    (4, "Última Parada"),
                ],
                null=True,
            ),
        ),
    ]
