# Generated by Django 6.0.5 on 2026-07-10 18:57

from django.db import migrations, models


def _decode_cod_barras(codbar):
    """Decodifica o código de barras da OP em (origem, op, estagio, seqrot)."""
    codbar = str(codbar or "").strip()
    if len(codbar) < 23:
        return None
    if len(codbar) == 23:
        origem = codbar[4:6]
        op = codbar[6:15]
        estagio = codbar[15:19]
        seqrot = codbar[19:23]
    else:
        origem = codbar[4:7]
        op = codbar[7:16]
        estagio = codbar[16:20]
        seqrot = codbar[20:24]
    try:
        return origem, int(op), int(estagio), int(seqrot)
    except TypeError, ValueError:
        return None


def preencher_campos_op(apps, schema_editor):
    LogTrocaOPAtiva = apps.get_model("accounts", "LogTrocaOPAtiva")
    ParadaMaquina = apps.get_model("accounts", "ParadaMaquina")

    for log in LogTrocaOPAtiva.objects.all():
        dados = _decode_cod_barras(log.codigo_barra_op)
        if not dados:
            continue
        log.origem, log.op, log.estagio, log.seqrot = dados
        log.save(update_fields=["origem", "op", "estagio", "seqrot"])

    for parada in ParadaMaquina.objects.all():
        dados = _decode_cod_barras(parada.op_ativa)
        if not dados:
            continue
        parada.origem, parada.op, parada.estagio, parada.seqrot = dados
        parada.save(update_fields=["origem", "op", "estagio", "seqrot"])


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_remove_recurso_desvio_pro_remove_recurso_tipo_parada_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="logtrocaopativa",
            name="data_hora",
            field=models.DateTimeField(auto_now=True, verbose_name="Data/Hora"),
        ),
        migrations.AddField(
            model_name="logtrocaopativa",
            name="estagio",
            field=models.IntegerField(blank=True, null=True, verbose_name="Estágio"),
        ),
        migrations.AddField(
            model_name="logtrocaopativa",
            name="log",
            field=models.TextField(blank=True, null=True, verbose_name="Log"),
        ),
        migrations.AddField(
            model_name="logtrocaopativa",
            name="op",
            field=models.IntegerField(blank=True, null=True, verbose_name="Ordem de Produção"),
        ),
        migrations.AddField(
            model_name="logtrocaopativa",
            name="origem",
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name="Origem"),
        ),
        migrations.AddField(
            model_name="logtrocaopativa",
            name="seqrot",
            field=models.IntegerField(blank=True, null=True, verbose_name="Seq. Roteiro"),
        ),
        migrations.AddField(
            model_name="logtrocaopativa",
            name="status",
            field=models.IntegerField(default=0, verbose_name="Status"),
        ),
        migrations.AddField(
            model_name="paradamaquina",
            name="data_hora",
            field=models.DateTimeField(auto_now=True, verbose_name="Data/Hora"),
        ),
        migrations.AddField(
            model_name="paradamaquina",
            name="estagio",
            field=models.IntegerField(blank=True, null=True, verbose_name="Estágio"),
        ),
        migrations.AddField(
            model_name="paradamaquina",
            name="log",
            field=models.TextField(blank=True, null=True, verbose_name="Log"),
        ),
        migrations.AddField(
            model_name="paradamaquina",
            name="op",
            field=models.IntegerField(blank=True, null=True, verbose_name="Ordem de Produção"),
        ),
        migrations.AddField(
            model_name="paradamaquina",
            name="origem",
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name="Origem"),
        ),
        migrations.AddField(
            model_name="paradamaquina",
            name="seqrot",
            field=models.IntegerField(blank=True, null=True, verbose_name="Seq. Roteiro"),
        ),
        migrations.AddField(
            model_name="paradamaquina",
            name="status",
            field=models.IntegerField(default=0, verbose_name="Status"),
        ),
        migrations.RunPython(preencher_campos_op, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="logtrocaopativa",
            name="codigo_barra_op",
        ),
        migrations.RemoveField(
            model_name="paradamaquina",
            name="op_ativa",
        ),
    ]
