# Generated by Django 6.0.5 on 2026-07-22 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0017_atualizar_motivoabrangencia_grupo_parada"),
    ]

    operations = [
        migrations.CreateModel(
            name="DispositivoNotificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("token", models.TextField(unique=True)),
                ("plataforma", models.CharField(default="android", max_length=20)),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispositivos_notificacao",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dispositivo de notificação",
                "verbose_name_plural": "Dispositivos de notificação",
                "db_table": "dispositivos_notificacao",
                "default_permissions": (),
            },
        ),
    ]
