# Generated by Django 6.0.5 on 2026-08-10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0020_normalizar_tempo_parada_aut_minimo_um_segundo"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurso",
            name="telemetria_encerra_parada_manual",
            field=models.BooleanField(
                default=False,
                verbose_name="Telemetria encerra parada manual",
            ),
        ),
    ]
