# Generated by Django 6.0.5 on 2026-08-10

from datetime import timedelta

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0021_recurso_telemetria_encerra_parada_manual"),
    ]

    operations = [
        migrations.AddField(
            model_name="recurso",
            name="tempo_minimo_parada",
            field=models.DurationField(
                default=timedelta(minutes=1),
                verbose_name="Tempo mínimo de parada",
            ),
        ),
    ]
