# Generated by Django 6.0.5 on 2026-08-29 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0023_normalizar_campos_texto"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoAplicacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("chave", models.CharField(max_length=100, unique=True, verbose_name="Chave")),
                ("valor", models.TextField(verbose_name="Valor")),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "atualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="configuracoes_alteradas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração da aplicação",
                "verbose_name_plural": "Configurações da aplicação",
                "db_table": "configuracoes_aplicacao",
                "ordering": ["chave"],
                "default_permissions": (),
            },
        ),
    ]
