# Generated by Django 6.0.5 on 2026-08-13

from django.db import migrations, models

PERMISSAO = "pode_visualizar_componentes_movimentar"


def mover_permissao_para_logistica(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")
    Group = apps.get_model("auth", "Group")
    User = apps.get_model("accounts", "CustomUser")

    origem_ct = ContentType.objects.filter(app_label="producao", model="permissoesproducao").first()
    destino_ct, _ = ContentType.objects.get_or_create(
        app_label="logistica", model="permissoeslogistica"
    )
    destino, _ = Permission.objects.get_or_create(
        codename=PERMISSAO,
        content_type=destino_ct,
        defaults={"name": "Pode visualizar Componentes a Movimentar"},
    )
    if not origem_ct:
        return

    origem = Permission.objects.filter(codename=PERMISSAO, content_type=origem_ct).first()
    if not origem:
        return

    for grupo in Group.objects.filter(permissions=origem):
        grupo.permissions.add(destino)
    for usuario in User.objects.filter(user_permissions=origem):
        usuario.user_permissions.add(destino)
    origem.delete()


def restaurar_permissao_producao(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")
    Group = apps.get_model("auth", "Group")
    User = apps.get_model("accounts", "CustomUser")

    destino_ct = ContentType.objects.filter(
        app_label="logistica", model="permissoeslogistica"
    ).first()
    origem_ct, _ = ContentType.objects.get_or_create(
        app_label="producao", model="permissoesproducao"
    )
    origem, _ = Permission.objects.get_or_create(
        codename=PERMISSAO,
        content_type=origem_ct,
        defaults={"name": "Pode Visualizar Componentes a Movimentar"},
    )
    if not destino_ct:
        return

    destino = Permission.objects.filter(codename=PERMISSAO, content_type=destino_ct).first()
    if not destino:
        return
    for grupo in Group.objects.filter(permissions=destino):
        grupo.permissions.add(origem)
    for usuario in User.objects.filter(user_permissions=destino):
        usuario.user_permissions.add(origem)
    destino.delete()


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("producao", "0038_remover_permissao_componentes_movimentar"),
    ]

    operations = [
        migrations.CreateModel(
            name="PermissoesLogistica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
            ],
            options={
                "managed": False,
                "default_permissions": (),
                "permissions": [
                    (PERMISSAO, "Pode visualizar Componentes a Movimentar"),
                ],
            },
        ),
        migrations.RunPython(mover_permissao_para_logistica, restaurar_permissao_producao),
    ]
