# Generated by Django 6.0.5 on 2026-08-26 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0023_normalizar_campos_texto"),
        ("telemetria", "0006_fonte_pausa_sucesso_padrao"),
    ]

    operations = [
        migrations.CreateModel(
            name="PermissoesTelemetria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
            ],
            options={
                "permissions": [("pode_gerenciar_sensores", "Pode gerenciar sensores")],
                "managed": False,
                "default_permissions": (),
            },
        ),
        migrations.AddField(
            model_name="fontecoletahttp",
            name="filial",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fontes_coleta_telemetria",
                to="accounts.filial",
                verbose_name="Filial",
            ),
        ),
        migrations.AddField(
            model_name="sensor",
            name="filial",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sensores_telemetria",
                to="accounts.filial",
                verbose_name="Filial",
            ),
        ),
    ]
