# Generated by Django 6.0.5 on 2026-06-30 21:27

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PermissoesChamado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("pode_manipular_chamados", "Pode manipular chamados"),
                    ("pode_listar_todos_chamados", "Pode listar todos os chamados"),
                    ("pode_manipular_os", "Pode manipular OS"),
                    ("pode_listar_todas_os", "Pode listar todos as OS"),
                    ("pode_acessar_os", "Pode acessar OS"),
                ],
                "managed": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Chamado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("ELETRICA", "Elétrica"),
                            ("MECANICA", "Mecânica"),
                            ("HIDRAULICA", "Hidráulica"),
                            ("PNEUMATICA", "Pneumática"),
                            ("MELHORIAS", "Melhorias"),
                            ("MANUTENCAO_INFRA", "Manutenção Infraestrutura"),
                            ("MANUTENCAO_LOGISTICA", "Manutenção Logística"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "prioridade",
                    models.CharField(
                        choices=[
                            ("BAIXA", "Baixa"),
                            ("MEDIA", "Média"),
                            ("ALTA", "Alta"),
                            ("CRITICA", "Crítica"),
                        ],
                        default="MEDIA",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ABERTO", "Aberto"),
                            ("EM_ATENDIMENTO", "Em atendimento"),
                            ("PENDENTE", "Pendente"),
                            ("FECHADO", "Fechado"),
                        ],
                        default="ABERTO",
                        max_length=20,
                    ),
                ),
                (
                    "responsaveis",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        default=list,
                        null=True,
                        verbose_name="IDs dos responsáveis",
                    ),
                ),
                (
                    "observadores_id",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        default=list,
                        null=True,
                        verbose_name="IDs dos observadores",
                    ),
                ),
                ("sla_previsto", models.DurationField(blank=True, null=True)),
                ("sla_realizado", models.DurationField(blank=True, null=True)),
                (
                    "recurso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="accounts.recurso"
                    ),
                ),
            ],
            options={
                "db_table": "chamado",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Interacao_Chamado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("mensagem", models.TextField()),
                ("data", models.DateTimeField(auto_now_add=True)),
                ("ultima_edicao", models.DateTimeField(auto_now=True)),
                (
                    "chamado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interacoeschamados",
                        to="manutencao.chamado",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "chamado_interacao",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="OrdemServico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "responsaveis",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        default=list,
                        null=True,
                        verbose_name="IDs dos responsáveis",
                    ),
                ),
                ("descricao", models.TextField(default=None)),
                ("inicio_prev", models.DateTimeField(blank=True, null=True)),
                ("final_prev", models.DateTimeField(blank=True, null=True)),
                ("inicio_real", models.DateTimeField(blank=True, null=True)),
                ("final_real", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ABERTA", "Aberta"),
                            ("EM_EXECUCAO", "Em execução"),
                            ("FINALIZADA", "Finalizada"),
                            ("CANCELADA", "Cancelada"),
                            ("PARADA", "Parada"),
                        ],
                        default="ABERTA",
                        max_length=20,
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "chamado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="manutencao.chamado",
                    ),
                ),
                (
                    "recurso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="accounts.recurso"
                    ),
                ),
            ],
            options={
                "db_table": "ordem_servico",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Interacao_OS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("inicio", models.DateTimeField(blank=True, null=True)),
                ("fim", models.DateTimeField(blank=True, null=True)),
                ("descricao", models.TextField(blank=True)),
                ("data_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ordem_servico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interacoesos",
                        to="manutencao.ordemservico",
                    ),
                ),
            ],
            options={
                "db_table": "ordem_servico_interacao",
                "default_permissions": (),
            },
        ),
    ]
