# Generated by Django 6.0.5 on 2026-07-15 18:10

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0015_motivoabrangencia_codtpm"),
        ("manutencao", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="chamado",
            index=models.Index(fields=["recurso", "-id"], name="idx_chamado_recurso_id"),
        ),
        migrations.AddIndex(
            model_name="chamado",
            index=models.Index(fields=["status", "-id"], name="idx_chamado_status_id"),
        ),
        migrations.AddIndex(
            model_name="chamado",
            index=models.Index(fields=["categoria", "-id"], name="idx_chamado_categoria_id"),
        ),
        migrations.AddIndex(
            model_name="chamado",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["responsaveis"], name="idx_chamado_responsaveis"
            ),
        ),
        migrations.AddIndex(
            model_name="chamado",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["observadores_id"], name="idx_chamado_observadores"
            ),
        ),
        migrations.AddIndex(
            model_name="interacao_chamado",
            index=models.Index(fields=["chamado", "data"], name="idx_interacao_chamado_data"),
        ),
        migrations.AddIndex(
            model_name="ordemservico",
            index=models.Index(fields=["recurso", "-id"], name="idx_os_recurso_id"),
        ),
        migrations.AddIndex(
            model_name="ordemservico",
            index=models.Index(fields=["status", "-id"], name="idx_os_status_id"),
        ),
        migrations.AddIndex(
            model_name="ordemservico",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["responsaveis"], name="idx_os_responsaveis"
            ),
        ),
    ]
