# Generated by Django 6.0.5 on 2026-07-15 18:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manutencao", "0002_chamado_idx_chamado_recurso_id_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="chamado",
            name="idx_chamado_status_id",
        ),
        migrations.RemoveIndex(
            model_name="chamado",
            name="idx_chamado_categoria_id",
        ),
        migrations.RemoveIndex(
            model_name="ordemservico",
            name="idx_os_status_id",
        ),
    ]
