# Generated by Django 6.0.5 on 2026-07-15 18:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manutencao", "0003_remove_chamado_idx_chamado_status_id_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="chamado",
            name="idx_chamado_responsaveis",
        ),
        migrations.RemoveIndex(
            model_name="chamado",
            name="idx_chamado_observadores",
        ),
        migrations.RemoveIndex(
            model_name="ordemservico",
            name="idx_os_responsaveis",
        ),
    ]
