# Generated by Django 6.0.5 on 2026-07-15 18:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manutencao", "0004_remove_chamado_idx_chamado_responsaveis_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="chamado",
            name="idx_chamado_recurso_id",
        ),
        migrations.RemoveIndex(
            model_name="interacao_chamado",
            name="idx_interacao_chamado_data",
        ),
        migrations.RemoveIndex(
            model_name="ordemservico",
            name="idx_os_recurso_id",
        ),
    ]
