# Generated by Django 6.0.5 on 2026-07-24 17:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manutencao", "0005_remove_chamado_idx_chamado_recurso_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="permissoeschamado",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": [
                    ("pode_acessar_chamados", "Pode acessar chamados"),
                    ("pode_manipular_chamados", "Pode manipular chamados"),
                    ("pode_listar_todos_chamados", "Pode listar todos os chamados"),
                    ("pode_manipular_os", "Pode manipular OS"),
                    ("pode_listar_todas_os", "Pode listar todos as OS"),
                    ("pode_acessar_os", "Pode acessar OS"),
                ],
            },
        ),
    ]
