# Generated by Django 6.0.5 on 2026-06-30 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE SCHEMA IF NOT EXISTS producao",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name="PermissoesProducao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("pode_acessar_sequenciamento", "Pode acessar Sequenciamento"),
                    ("pode_consolidar_sequenciamento_erp", "Pode consolidar Sequenciamento ERP"),
                    ("pode_corrigir_lote", "Pode corrigir Lote"),
                    ("pode_acessar_relatorios_producao", "Pode acessar Relatórios de Produção"),
                ],
                "managed": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="EstornoComponente",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("codemp", models.IntegerField(default=1, verbose_name="Empresa")),
                ("acodori", models.CharField(max_length=10, verbose_name="Origem")),
                ("anumorp", models.IntegerField(verbose_name="Ordem de Produção")),
                ("acodetg", models.IntegerField(verbose_name="Estágio")),
                (
                    "acodpro",
                    models.CharField(blank=True, max_length=50, null=True, verbose_name="Produto"),
                ),
                (
                    "acodder",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Derivação"
                    ),
                ),
                (
                    "acodcmp",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Componente"
                    ),
                ),
                (
                    "adercmp",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Derivação Componente"
                    ),
                ),
                (
                    "aqtdest",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        verbose_name="Qtd. Estorno",
                    ),
                ),
                ("adatfim", models.DateField(verbose_name="Data Fim")),
                ("acodtns", models.CharField(max_length=10, verbose_name="Transação")),
                (
                    "lote",
                    models.CharField(blank=True, max_length=50, null=True, verbose_name="Lote"),
                ),
                ("status", models.IntegerField(default=0, verbose_name="Status")),
                ("log", models.TextField(blank=True, null=True, verbose_name="Log do Webservice")),
                ("data_hora", models.DateTimeField(auto_now=True, verbose_name="Data/Hora Log")),
            ],
            options={
                "verbose_name": "Estorno de Componente",
                "verbose_name_plural": "Estornos de Componentes",
                "db_table": 'producao"."estorno_comp',
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Apontamento",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("codemp", models.IntegerField(verbose_name="Empresa")),
                ("origem", models.CharField(max_length=10, verbose_name="Origem")),
                ("numorp", models.IntegerField(verbose_name="Ordem de Produção")),
                ("codetg", models.IntegerField(verbose_name="Estágio")),
                ("seqrot", models.IntegerField(verbose_name="Seq. Roteiro")),
                ("numcad", models.IntegerField(verbose_name="Operador")),
                (
                    "qtdre1",
                    models.DecimalField(decimal_places=4, max_digits=12, verbose_name="Quantidade"),
                ),
                (
                    "qtdrfg",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=12, verbose_name="Refugo"
                    ),
                ),
                (
                    "lote",
                    models.CharField(blank=True, max_length=50, null=True, verbose_name="Lote"),
                ),
                ("log", models.TextField(blank=True, null=True, verbose_name="Log do Webservice")),
                ("status", models.IntegerField(default=0, verbose_name="Status")),
                ("data_hora", models.DateTimeField(auto_now=True, verbose_name="Data/Hora")),
                (
                    "codigo_integrador",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Código Integrador"
                    ),
                ),
                (
                    "datmov",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Data Movimento"
                    ),
                ),
                (
                    "hormov",
                    models.CharField(
                        blank=True, max_length=8, null=True, verbose_name="Hora Movimento"
                    ),
                ),
                ("bobina", models.IntegerField(blank=True, null=True, verbose_name="Bobina Atual")),
                (
                    "origem_peso",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Origem do Peso"
                    ),
                ),
                (
                    "balanca",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=12,
                        null=True,
                        verbose_name="Balança",
                    ),
                ),
                (
                    "recurso",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="apontamentos",
                        to="accounts.recurso",
                        verbose_name="Recurso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Apontamento Sapiens",
                "verbose_name_plural": "Apontamentos Sapiens",
                "db_table": 'producao"."apontamento',
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="ApontamentoComponente",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("codemp", models.IntegerField(verbose_name="Empresa")),
                ("origem", models.CharField(max_length=10, verbose_name="Origem")),
                ("numorp", models.IntegerField(verbose_name="Ordem de Produção")),
                ("codetg", models.IntegerField(verbose_name="Estágio")),
                ("seqrot", models.IntegerField(verbose_name="Seq. Roteiro")),
                ("numcad", models.IntegerField(verbose_name="Operador")),
                (
                    "codigo_integrador",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Código Integrador"
                    ),
                ),
                (
                    "datmov",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Data Movimento"
                    ),
                ),
                (
                    "hormov",
                    models.CharField(
                        blank=True, max_length=8, null=True, verbose_name="Hora Movimento"
                    ),
                ),
                ("lote", models.CharField(max_length=50, verbose_name="Lote")),
                ("log", models.TextField(blank=True, null=True, verbose_name="Log do Webservice")),
                ("status", models.IntegerField(default=0, verbose_name="Status")),
                ("data_hora", models.DateTimeField(auto_now=True, verbose_name="Data/Hora")),
                (
                    "recurso",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="apontamentos_componentes",
                        to="accounts.recurso",
                        verbose_name="Recurso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Apontamento de Componente",
                "verbose_name_plural": "Apontamentos de Componentes",
                "db_table": 'producao"."apontamento_componente',
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Sequenciamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ordenacao", models.IntegerField(verbose_name="Ordenação")),
                ("op", models.IntegerField(verbose_name="Ordem de Produção")),
                ("origem", models.CharField(max_length=10, verbose_name="Origem")),
                ("codproduto", models.CharField(max_length=50, verbose_name="Código do Produto")),
                (
                    "descricao",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Descrição"
                    ),
                ),
                (
                    "derivacao",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Derivação"
                    ),
                ),
                ("estagio", models.IntegerField(verbose_name="Estágio")),
                ("seqroteiro", models.IntegerField(verbose_name="Seq. Roteiro")),
                ("tempo", models.FloatField(verbose_name="Tempo")),
                ("operacao", models.CharField(max_length=100, verbose_name="Operação")),
                (
                    "recurso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sequenciamentos",
                        to="accounts.recurso",
                        verbose_name="Recurso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sequenciamento",
                "verbose_name_plural": "Sequenciamentos",
                "db_table": 'producao"."sequenciamento',
                "ordering": ["ordenacao"],
                "default_permissions": (),
            },
        ),
    ]
