# Generated by Django 6.0.5 on 2026-07-10 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_rename_campos_paradamaquina"),
        ("producao", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LogParada",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("codemp", models.IntegerField(blank=True, null=True, verbose_name="Empresa")),
                (
                    "origem",
                    models.CharField(blank=True, max_length=10, null=True, verbose_name="Origem"),
                ),
                (
                    "numorp",
                    models.IntegerField(blank=True, null=True, verbose_name="Ordem de Produção"),
                ),
                ("codetg", models.IntegerField(blank=True, null=True, verbose_name="Estágio")),
                ("seqrot", models.IntegerField(blank=True, null=True, verbose_name="Seq. Roteiro")),
                ("numcad", models.IntegerField(blank=True, null=True, verbose_name="Operador")),
                (
                    "codigo_integrador",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Código Integrador"
                    ),
                ),
                (
                    "datmov",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Data Movimento"
                    ),
                ),
                (
                    "hormov",
                    models.CharField(
                        blank=True, max_length=8, null=True, verbose_name="Hora Movimento"
                    ),
                ),
                (
                    "op_ativa",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="OP Ativa"
                    ),
                ),
                (
                    "operador",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Operador"
                    ),
                ),
                (
                    "motivo",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="Motivo"),
                ),
                ("tipo", models.SmallIntegerField(blank=True, null=True, verbose_name="Tipo")),
                (
                    "inicio",
                    models.DateTimeField(blank=True, null=True, verbose_name="Data/Hora Início"),
                ),
                ("fim", models.DateTimeField(blank=True, null=True, verbose_name="Data/Hora Fim")),
                (
                    "hora_log",
                    models.DateTimeField(blank=True, null=True, verbose_name="Data/Hora Log"),
                ),
                (
                    "log_integracao",
                    models.TextField(blank=True, null=True, verbose_name="Log Integração"),
                ),
                ("status", models.IntegerField(default=0, verbose_name="Status")),
                ("data_hora", models.DateTimeField(auto_now=True, verbose_name="Data/Hora")),
                (
                    "parada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="logs_parada",
                        to="accounts.paradamaquina",
                        verbose_name="Parada",
                    ),
                ),
                (
                    "recurso",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="logs_parada",
                        to="accounts.recurso",
                        verbose_name="Recurso",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs_parada_registrados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Parada",
                "verbose_name_plural": "Logs de Parada",
                "db_table": 'producao"."logs_parada',
                "ordering": ["-data_hora", "-id"],
                "default_permissions": (),
            },
        ),
    ]
