# Generated by Django 6.0.5 on 2026-07-10 21:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("producao", "0005_reordenar_colunas_tabelas_sigma"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="logparada",
            name="op_ativa",
        ),
    ]
