# Generated by Django 6.0.5 on 2026-07-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("producao", "0008_registrar_paradamaquina_em_producao"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paradamaquina",
            name="data_hora",
        ),
        migrations.AlterField(
            model_name="paradamaquina",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
