# Generated by Django 6.0.5 on 2026-07-10 21:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("producao", "0014_reordenar_paradamaquina_com_troca"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="paradamaquina",
            name="uniq_parada_aberta_recurso",
        ),
        migrations.RemoveIndex(
            model_name="paradamaquina",
            name="idx_parada_recurso_fim",
        ),
        migrations.AddIndex(
            model_name="paradamaquina",
            index=models.Index(fields=["troca_op_ativa", "fim"], name="idx_parada_troca_fim"),
        ),
        migrations.AddConstraint(
            model_name="paradamaquina",
            constraint=models.UniqueConstraint(
                condition=models.Q(("fim__isnull", True)),
                fields=("troca_op_ativa",),
                name="uniq_parada_aberta_troca",
            ),
        ),
        migrations.RemoveField(
            model_name="paradamaquina",
            name="recurso",
        ),
    ]
