# Generated by Django 6.0.5 on 2026-07-15 18:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0015_motivoabrangencia_codtpm"),
        ("producao", "0021_logtrocaopativa_usuario"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="apontamento",
            index=models.Index(fields=["codemp", "-id"], name="idx_apont_codemp_id"),
        ),
        migrations.AddIndex(
            model_name="apontamento",
            index=models.Index(
                fields=["status", "codemp", "origem", "numorp", "codetg", "seqrot", "id"],
                name="idx_apont_fila_chave",
            ),
        ),
        migrations.AddIndex(
            model_name="apontamentocomponente",
            index=models.Index(fields=["codemp", "-id"], name="idx_comp_codemp_id"),
        ),
        migrations.AddIndex(
            model_name="apontamentocomponente",
            index=models.Index(
                fields=["status", "codemp", "origem", "numorp", "codetg", "seqrot"],
                name="idx_comp_fila_chave",
            ),
        ),
        migrations.AddIndex(
            model_name="estornocomponente",
            index=models.Index(fields=["status", "adatfim"], name="idx_estorno_status_data"),
        ),
        migrations.AddIndex(
            model_name="logtrocaopativa",
            index=models.Index(fields=["-horario_troca", "-id"], name="idx_log_op_troca_id"),
        ),
    ]
