# Generated by Django 6.0.5 on 2026-07-15 18:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("producao", "0022_apontamento_idx_apont_codemp_id_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="apontamento",
            name="idx_apont_codemp_id",
        ),
        migrations.RemoveIndex(
            model_name="apontamentocomponente",
            name="idx_comp_codemp_id",
        ),
    ]
