# Generated by Django 6.0.5 on 2026-07-15 18:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0015_motivoabrangencia_codtpm"),
        ("producao", "0023_remove_apontamento_idx_apont_codemp_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="apontamento",
            name="idx_apont_fila_chave",
        ),
        migrations.RemoveIndex(
            model_name="apontamentocomponente",
            name="idx_comp_fila_chave",
        ),
        migrations.RemoveIndex(
            model_name="estornocomponente",
            name="idx_estorno_status_data",
        ),
        migrations.AddIndex(
            model_name="apontamento",
            index=models.Index(fields=["codemp", "-id"], name="idx_apont_codemp_id"),
        ),
        migrations.AddIndex(
            model_name="apontamentocomponente",
            index=models.Index(fields=["codemp", "-id"], name="idx_comp_codemp_id"),
        ),
    ]
