# Generated by Django 6.0.5 on 2026-07-15 18:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0015_motivoabrangencia_codtpm"),
        ("producao", "0024_remove_apontamento_idx_apont_fila_chave_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="apontamento",
            index=models.Index(
                fields=["status", "codemp", "origem", "numorp", "codetg", "seqrot", "id"],
                name="idx_apont_fila_chave",
            ),
        ),
        migrations.AddIndex(
            model_name="apontamentocomponente",
            index=models.Index(
                fields=["status", "codemp", "origem", "numorp", "codetg", "seqrot"],
                name="idx_comp_fila_chave",
            ),
        ),
        migrations.AddIndex(
            model_name="estornocomponente",
            index=models.Index(fields=["status", "adatfim"], name="idx_estorno_status_data"),
        ),
    ]
