# Generated by Django 6.0.5 on 2026-07-15 19:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("producao", "0025_apontamento_idx_apont_fila_chave_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="logtrocaopativa",
            name="status",
        ),
        migrations.RemoveField(
            model_name="paradamaquina",
            name="status",
        ),
    ]
