# Generated by Django 6.0.5 on 2026-07-15 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("producao", "0026_remove_logtrocaopativa_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PacoteTempoERP",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("corte_inicio_real", models.DateTimeField(verbose_name="Corte Início Real")),
                ("corte_fim_real", models.DateTimeField(verbose_name="Corte Fim Real")),
                ("log", models.TextField(blank=True, null=True, verbose_name="Log")),
                (
                    "data_hora_log",
                    models.DateTimeField(auto_now=True, verbose_name="Data/Hora Log"),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(0, "Pendente"), (1, "Enviado"), (2, "Erro")],
                        default=0,
                        verbose_name="Status",
                    ),
                ),
                (
                    "troca_op_ativa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pacotes_tempo_erp",
                        to="producao.logtrocaopativa",
                        verbose_name="Troca de OP Ativa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pacote de Tempo ERP",
                "verbose_name_plural": "Pacotes de Tempo ERP",
                "db_table": 'producao"."pacotes_tempo_erp',
                "ordering": ["-corte_fim_real", "-id"],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="ItemPacoteTempoERP",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "tipo_registro",
                    models.CharField(
                        choices=[("PRODUCAO", "Produção"), ("PARADA", "Parada")],
                        max_length=10,
                        verbose_name="Tipo de Registro",
                    ),
                ),
                ("operador", models.IntegerField(verbose_name="Operador")),
                (
                    "motivo",
                    models.CharField(
                        blank=True, max_length=4, null=True, verbose_name="Motivo ERP"
                    ),
                ),
                ("data_inicio", models.DateField(verbose_name="Data Início")),
                ("hora_inicio", models.TimeField(verbose_name="Hora Início")),
                ("data_fim", models.DateField(verbose_name="Data Fim")),
                ("hora_fim", models.TimeField(verbose_name="Hora Fim")),
                (
                    "pacote_tempo_erp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="producao.pacotetempoerp",
                        verbose_name="Pacote de Tempo ERP",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Pacote de Tempo ERP",
                "verbose_name_plural": "Itens de Pacote de Tempo ERP",
                "db_table": 'producao"."itens_pacote_tempo_erp',
                "ordering": ["id"],
                "default_permissions": (),
            },
        ),
        migrations.AddIndex(
            model_name="pacotetempoerp",
            index=models.Index(
                fields=["-corte_fim_real", "-id"], name="idx_pacote_tempo_erp_corte"
            ),
        ),
        migrations.AddConstraint(
            model_name="pacotetempoerp",
            constraint=models.UniqueConstraint(
                fields=("troca_op_ativa", "corte_inicio_real", "corte_fim_real"),
                name="uq_pacote_tempo_erp_corte",
            ),
        ),
    ]
