# Generated by Django 6.0.5 on 2026-07-15 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("producao", "0027_pacotetempoerp_itempacotetempoerp_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="pacotetempoerp",
            index=models.Index(
                fields=["troca_op_ativa", "-corte_fim_real"], name="idx_pacote_tempo_erp_troca"
            ),
        ),
    ]
