# Generated by Django 6.0.5 on 2026-07-21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0017_atualizar_motivoabrangencia_grupo_parada"),
        ("producao", "0030_pacotetempoerp_status_processando"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegraParadaRecurso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "ativa",
                    models.BooleanField(default=False, verbose_name="Regra automática ativa"),
                ),
                (
                    "regra",
                    models.JSONField(blank=True, default=dict, verbose_name="Regra de parada"),
                ),
                (
                    "recurso",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regra_parada_automatica",
                        to="accounts.recurso",
                        verbose_name="Recurso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regra automática de parada do recurso",
                "verbose_name_plural": "Regras automáticas de parada dos recursos",
                "db_table": 'producao"."regras_parada_recursos',
                "default_permissions": (),
            },
        ),
    ]
