# Generated by Django 6.0.5 on 2026-08-10 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0022_recurso_tempo_minimo_parada"),
        ("producao", "0033_paradamaquina_recurso_periodos_produtivos"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BobinaConsumoRecurso",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("codemp", models.IntegerField(verbose_name="Empresa")),
                ("lote", models.CharField(max_length=50, verbose_name="Lote")),
                (
                    "codpro",
                    models.CharField(blank=True, max_length=50, null=True, verbose_name="Produto"),
                ),
                (
                    "codder",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Derivação"
                    ),
                ),
                (
                    "quantidade_alocada",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="Quantidade Alocada"
                    ),
                ),
                (
                    "quantidade_restante",
                    models.DecimalField(
                        decimal_places=4, max_digits=12, verbose_name="Quantidade Restante"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Em fila"), (1, "Em consumo"), (2, "Finalizado")],
                        default=0,
                        verbose_name="Status",
                    ),
                ),
                (
                    "ordem_fila",
                    models.IntegerField(blank=True, null=True, verbose_name="Ordem na Fila"),
                ),
                (
                    "data_hora_alocacao",
                    models.DateTimeField(auto_now_add=True, verbose_name="Data/Hora Alocação"),
                ),
                (
                    "data_hora_status",
                    models.DateTimeField(auto_now=True, verbose_name="Data/Hora Status"),
                ),
                (
                    "recurso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bobinas_consumo",
                        to="accounts.recurso",
                        verbose_name="Recurso",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bobinas_consumo_alocadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bobina em Consumo do Recurso",
                "verbose_name_plural": "Bobinas em Consumo do Recurso",
                "db_table": 'producao"."bobinas_consumo_recurso',
                "ordering": ["status", "ordem_fila", "id"],
                "default_permissions": (),
                "indexes": [
                    models.Index(
                        fields=["recurso", "status", "ordem_fila"], name="idx_bobina_consumo_fila"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", [0, 1])),
                        fields=("recurso", "lote"),
                        name="uq_bobina_consumo_lote_ativo",
                    )
                ],
            },
        ),
    ]
