# Generated by Django 6.0.5 on 2026-08-11 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0022_recurso_tempo_minimo_parada"),
        ("producao", "0034_bobinaconsumorecurso"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BaixaComponente",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("codemp", models.IntegerField(verbose_name="Empresa")),
                ("origem", models.CharField(max_length=10, verbose_name="Origem")),
                ("numorp", models.IntegerField(verbose_name="Ordem de Produção")),
                ("codetg", models.IntegerField(verbose_name="Estágio")),
                ("seqrot", models.IntegerField(verbose_name="Seq. Roteiro")),
                (
                    "lotdes",
                    models.CharField(
                        max_length=50, verbose_name="Lote Destino (Produto Produzido)"
                    ),
                ),
                ("codcmp", models.CharField(max_length=50, verbose_name="Componente")),
                (
                    "dercmp",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Derivação Componente"
                    ),
                ),
                (
                    "qtduti",
                    models.DecimalField(
                        decimal_places=4, max_digits=14, verbose_name="Quantidade Utilizada"
                    ),
                ),
                (
                    "codigo_integrador",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Código Integrador"
                    ),
                ),
                (
                    "datmov",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Data Movimento"
                    ),
                ),
                (
                    "hormov",
                    models.CharField(
                        blank=True, max_length=8, null=True, verbose_name="Hora Movimento"
                    ),
                ),
                (
                    "codlot",
                    models.CharField(max_length=50, verbose_name="Lote da Bobina em Consumo"),
                ),
                (
                    "repesagem",
                    models.CharField(default="N", max_length=1, verbose_name="Repesagem (S/N)"),
                ),
                (
                    "consumototal",
                    models.CharField(default="N", max_length=1, verbose_name="Consumo Total (S/N)"),
                ),
                ("log", models.TextField(blank=True, null=True, verbose_name="Log do Webservice")),
                ("status", models.IntegerField(default=0, verbose_name="Status")),
                ("data_hora", models.DateTimeField(verbose_name="Data/Hora")),
                (
                    "recurso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="baixas_componentes",
                        to="accounts.recurso",
                        verbose_name="Recurso",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="baixas_componentes_registradas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Baixa de Componente",
                "verbose_name_plural": "Baixas de Componentes",
                "db_table": 'producao"."baixa_componentes',
                "default_permissions": (),
                "indexes": [
                    models.Index(fields=["codemp", "-id"], name="idx_baixa_comp_codemp_id"),
                    models.Index(
                        fields=["status", "codemp", "origem", "numorp", "codetg", "seqrot"],
                        name="idx_baixa_comp_fila_chave",
                    ),
                ],
            },
        ),
    ]
