# Generated by Django 6.0.5 on 2026-08-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("producao", "0035_baixacomponente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baixacomponente",
            name="lotdes",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Lote Destino (Produto Produzido)",
            ),
        ),
    ]
