# Generated by Django 6.0.5 on 2026-08-11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("producao", "0036_alter_baixacomponente_lotdes"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="baixacomponente",
            index=models.Index(fields=["status", "codlot", "id"], name="idx_baixa_comp_fila_lote"),
        ),
    ]
