# Generated by Django 6.0.5 on 2026-08-24 15:02

from django.db import migrations, models


def preencher_textos_nulos(apps, schema_editor):
    campos_por_modelo = {
        "Apontamento": ["codigo_integrador", "datmov", "hormov", "log", "lote", "origem_peso"],
        "ApontamentoComponente": ["codigo_integrador", "datmov", "hormov", "log"],
        "BaixaComponente": ["codigo_integrador", "datmov", "dercmp", "hormov", "log", "lotdes"],
        "BobinaConsumoRecurso": ["codder", "codpro"],
        "EstornoComponente": ["acodcmp", "acodder", "acodpro", "adercmp", "log", "lote"],
        "ItemPacoteTempoERP": ["motivo"],
        "LogTrocaOPAtiva": ["log", "origem"],
        "PacoteTempoERP": ["log"],
        "Sequenciamento": ["derivacao", "descricao"],
    }
    for nome_modelo, campos in campos_por_modelo.items():
        modelo = apps.get_model("producao", nome_modelo)
        for campo in campos:
            modelo.objects.filter(**{f"{campo}__isnull": True}).update(**{campo: ""})


class Migration(migrations.Migration):
    dependencies = [
        ("producao", "0038_remover_permissao_componentes_movimentar"),
    ]

    operations = [
        migrations.RunPython(preencher_textos_nulos, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="apontamento",
            name="codigo_integrador",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Código Integrador"
            ),
        ),
        migrations.AlterField(
            model_name="apontamento",
            name="datmov",
            field=models.CharField(
                blank=True, default="", max_length=10, verbose_name="Data Movimento"
            ),
        ),
        migrations.AlterField(
            model_name="apontamento",
            name="hormov",
            field=models.CharField(
                blank=True, default="", max_length=8, verbose_name="Hora Movimento"
            ),
        ),
        migrations.AlterField(
            model_name="apontamento",
            name="log",
            field=models.TextField(blank=True, default="", verbose_name="Log do Webservice"),
        ),
        migrations.AlterField(
            model_name="apontamento",
            name="lote",
            field=models.CharField(blank=True, default="", max_length=50, verbose_name="Lote"),
        ),
        migrations.AlterField(
            model_name="apontamento",
            name="origem_peso",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="Origem do Peso"
            ),
        ),
        migrations.AlterField(
            model_name="apontamentocomponente",
            name="codigo_integrador",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Código Integrador"
            ),
        ),
        migrations.AlterField(
            model_name="apontamentocomponente",
            name="datmov",
            field=models.CharField(
                blank=True, default="", max_length=10, verbose_name="Data Movimento"
            ),
        ),
        migrations.AlterField(
            model_name="apontamentocomponente",
            name="hormov",
            field=models.CharField(
                blank=True, default="", max_length=8, verbose_name="Hora Movimento"
            ),
        ),
        migrations.AlterField(
            model_name="apontamentocomponente",
            name="log",
            field=models.TextField(blank=True, default="", verbose_name="Log do Webservice"),
        ),
        migrations.AlterField(
            model_name="baixacomponente",
            name="codigo_integrador",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Código Integrador"
            ),
        ),
        migrations.AlterField(
            model_name="baixacomponente",
            name="datmov",
            field=models.CharField(
                blank=True, default="", max_length=10, verbose_name="Data Movimento"
            ),
        ),
        migrations.AlterField(
            model_name="baixacomponente",
            name="dercmp",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Derivação Componente"
            ),
        ),
        migrations.AlterField(
            model_name="baixacomponente",
            name="hormov",
            field=models.CharField(
                blank=True, default="", max_length=8, verbose_name="Hora Movimento"
            ),
        ),
        migrations.AlterField(
            model_name="baixacomponente",
            name="log",
            field=models.TextField(blank=True, default="", verbose_name="Log do Webservice"),
        ),
        migrations.AlterField(
            model_name="baixacomponente",
            name="lotdes",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                verbose_name="Lote Destino (Produto Produzido)",
            ),
        ),
        migrations.AlterField(
            model_name="bobinaconsumorecurso",
            name="codder",
            field=models.CharField(blank=True, default="", max_length=50, verbose_name="Derivação"),
        ),
        migrations.AlterField(
            model_name="bobinaconsumorecurso",
            name="codpro",
            field=models.CharField(blank=True, default="", max_length=50, verbose_name="Produto"),
        ),
        migrations.AlterField(
            model_name="estornocomponente",
            name="acodcmp",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Componente"
            ),
        ),
        migrations.AlterField(
            model_name="estornocomponente",
            name="acodder",
            field=models.CharField(blank=True, default="", max_length=50, verbose_name="Derivação"),
        ),
        migrations.AlterField(
            model_name="estornocomponente",
            name="acodpro",
            field=models.CharField(blank=True, default="", max_length=50, verbose_name="Produto"),
        ),
        migrations.AlterField(
            model_name="estornocomponente",
            name="adercmp",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Derivação Componente"
            ),
        ),
        migrations.AlterField(
            model_name="estornocomponente",
            name="log",
            field=models.TextField(blank=True, default="", verbose_name="Log do Webservice"),
        ),
        migrations.AlterField(
            model_name="estornocomponente",
            name="lote",
            field=models.CharField(blank=True, default="", max_length=50, verbose_name="Lote"),
        ),
        migrations.AlterField(
            model_name="itempacotetempoerp",
            name="motivo",
            field=models.CharField(blank=True, default="", max_length=4, verbose_name="Motivo ERP"),
        ),
        migrations.AlterField(
            model_name="logtrocaopativa",
            name="log",
            field=models.TextField(blank=True, default="", verbose_name="Log"),
        ),
        migrations.AlterField(
            model_name="logtrocaopativa",
            name="origem",
            field=models.CharField(blank=True, default="", max_length=10, verbose_name="Origem"),
        ),
        migrations.AlterField(
            model_name="pacotetempoerp",
            name="log",
            field=models.TextField(blank=True, default="", verbose_name="Log"),
        ),
        migrations.AlterField(
            model_name="sequenciamento",
            name="derivacao",
            field=models.CharField(blank=True, default="", max_length=50, verbose_name="Derivação"),
        ),
        migrations.AlterField(
            model_name="sequenciamento",
            name="descricao",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Descrição"
            ),
        ),
    ]
