# Generated by Django 6.0.5 on 2026-08-24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("producao", "0039_normalizar_campos_texto"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorrecaoLote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("codemp", models.IntegerField(verbose_name="Empresa")),
                ("lote", models.CharField(max_length=50, verbose_name="Lote")),
                (
                    "quantidade",
                    models.DecimalField(decimal_places=4, max_digits=12, verbose_name="Quantidade"),
                ),
                (
                    "excluir_apontamento",
                    models.BooleanField(default=False, verbose_name="Excluir apontamento"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("EM_ANDAMENTO", "Em andamento"),
                            ("CONCLUIDA", "Concluída"),
                            ("FALHA", "Falha antes do ERP"),
                            ("CONCILIACAO", "Requer conciliação"),
                        ],
                        default="EM_ANDAMENTO",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("mensagem", models.TextField(blank=True, default="", verbose_name="Resultado")),
                (
                    "iniciado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Iniciado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Correção de lote",
                "verbose_name_plural": "Correções de lote",
                "db_table": 'producao"."correcao_lote',
                "default_permissions": (),
            },
        ),
        migrations.AddConstraint(
            model_name="correcaolote",
            constraint=models.UniqueConstraint(
                fields=("codemp", "lote"), name="uniq_correcao_lote_empresa"
            ),
        ),
    ]
