# Generated by Django 6.0.5 on 2026-08-24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0023_normalizar_campos_texto"),
        ("producao", "0040_correcao_lote"),
    ]

    operations = [
        migrations.AddField(
            model_name="correcaolote",
            name="conciliacao_observacao",
            field=models.TextField(
                blank=True, default="", verbose_name="Observação da conciliação"
            ),
        ),
        migrations.AddField(
            model_name="correcaolote",
            name="conciliado_em",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Conciliado em"),
        ),
        migrations.AddField(
            model_name="correcaolote",
            name="conciliado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="correcoes_lote_conciliadas",
                to="accounts.customuser",
                verbose_name="Conciliado por",
            ),
        ),
    ]
