# Generated by Django 6.0.5 on 2026-08-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("producao", "0041_correcao_lote_conciliacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="correcaolote",
            name="status",
            field=models.CharField(
                choices=[
                    ("EM_ANDAMENTO", "Em andamento"),
                    ("CONCLUIDA", "Concluída"),
                    ("FALHA", "Falha"),
                    ("CONCILIACAO", "Conciliação"),
                ],
                default="EM_ANDAMENTO",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
