# Generated by Django 6.0.5 on 2026-08-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("producao", "0042_alter_correcaolote_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apontamento",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Não integrado"),
                    (1, "Integrado"),
                    (2, "Processando"),
                    (3, "Excluído"),
                ],
                default=0,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="apontamentocomponente",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Não integrado"),
                    (1, "Integrado"),
                    (2, "Processando"),
                    (3, "Excluído"),
                ],
                default=0,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="baixacomponente",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Não integrado"),
                    (1, "Integrado"),
                    (2, "Processando"),
                    (3, "Excluído"),
                ],
                default=0,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="estornocomponente",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Não integrado"), (1, "Integrado"), (2, "Processando")],
                default=0,
                verbose_name="Status",
            ),
        ),
    ]
