# Generated by Django 6.0.5 on 2026-08-25 17:41
# Reenumeração do status de EstornoComponente para espelhar o ciclo de vida
# de PacoteTempoERP (PENDENTE/ENVIADO/ERRO/PROCESSANDO): o valor 2, que era
# PROCESSANDO, passa a significar ERRO; PROCESSANDO vira 3.

from django.db import migrations, models


def renumerar_processando_para_novo_valor(apps, schema_editor):
    """Move o antigo PROCESSANDO (2) para o novo PROCESSANDO (3), antes do AlterField.

    Sem este passe, todo registro reservado por um worker passaria a ser lido
    como ERRO pela aplicação já migrada — mesmo significado, número diferente.
    Update em batch: uma única instrução UPDATE, sem carregar linhas em memória.
    """
    EstornoComponente = apps.get_model("producao", "EstornoComponente")
    EstornoComponente.objects.filter(status=2).update(status=3)


def renumerar_processando_para_valor_antigo(apps, schema_editor):
    """Reverso exato: devolve o PROCESSANDO (3) para o valor antigo (2)."""
    EstornoComponente = apps.get_model("producao", "EstornoComponente")
    EstornoComponente.objects.filter(status=3).update(status=2)


class Migration(migrations.Migration):
    dependencies = [
        ("producao", "0043_alter_apontamento_status_and_more"),
    ]

    operations = [
        # O passe de dados roda antes do AlterField: choices não são restrição
        # de banco, mas manter a ordem dado-antes-esquema evita janela em que
        # o Django novo interpretaria 2 (processando real) como erro.
        migrations.RunPython(
            renumerar_processando_para_novo_valor,
            renumerar_processando_para_valor_antigo,
            elidable=False,
        ),
        migrations.AlterField(
            model_name="estornocomponente",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Não integrado"), (1, "Integrado"), (2, "Erro"), (3, "Processando")],
                default=0,
                verbose_name="Status",
            ),
        ),
    ]
