# Generated by Django 6.0.5 on 2026-08-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("producao", "0044_alter_estornocomponente_status_and_renumera_processando"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="correcaolote",
            name="conciliacao_observacao",
        ),
        migrations.RemoveField(
            model_name="correcaolote",
            name="conciliado_em",
        ),
        migrations.RemoveField(
            model_name="correcaolote",
            name="conciliado_por",
        ),
        migrations.AlterField(
            model_name="correcaolote",
            name="status",
            field=models.CharField(
                choices=[
                    ("EM_ANDAMENTO", "Em andamento"),
                    ("CONCLUIDA", "Concluída"),
                    ("FALHA", "Falha"),
                ],
                default="EM_ANDAMENTO",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
