# Generated by Django 6.0.5 on 2026-08-29 01:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("producao", "0048_alter_permissoesproducao_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="apontamento",
            name="datger",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Data/Hora Geração"),
        ),
        migrations.AddField(
            model_name="apontamentocomponente",
            name="datger",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Data/Hora Geração"),
        ),
        migrations.AddField(
            model_name="baixacomponente",
            name="datger",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Data/Hora Geração"),
        ),
        migrations.AddField(
            model_name="pacotetempoerp",
            name="datger",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Data/Hora Geração"),
        ),
    ]
