# Generated by Django 6.0.5 on 2026-08-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("producao", "0049_datger_filas_integracao"),
    ]

    operations = [
        migrations.CreateModel(
            name="EstadoRelatorioFalhas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "ultimo_envio_em",
                    models.DateTimeField(blank=True, null=True, verbose_name="Último envio"),
                ),
            ],
            options={
                "verbose_name": "Estado do relatório de falhas",
                "verbose_name_plural": "Estado do relatório de falhas",
                "db_table": 'producao"."estado_relatorio_falhas',
                "default_permissions": (),
            },
        ),
    ]
