# Generated by Django 6.0.5 on 2026-08-13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PermissoesSuprimentos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
            ],
            options={
                "managed": False,
                "default_permissions": (),
                "permissions": [
                    (
                        "pode_visualizar_componentes_separar",
                        "Pode visualizar Componentes a Separar",
                    ),
                ],
            },
        ),
    ]
