# Generated by Django 6.0.5 on 2026-06-30 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE SCHEMA IF NOT EXISTS qualidade",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name="PermissoesQualidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("pode_liberar_bobinas", "Pode liberar lotes"),
                    ("pode_area_vermelha_bobinas", "Pode transferir lotes para área vermelha"),
                    (
                        "pode_liberar_area_vermelha",
                        "Pode acessar a tela de liberação da área vermelha",
                    ),
                    ("pode_destinar_area_vermelha", "Pode destinar lotes na área vermelha"),
                    (
                        "pode_cadastrar_observacoes_etiqueta",
                        "Pode cadastrar observações de etiqueta",
                    ),
                ],
                "managed": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="ObservacaoEtiqueta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=255, unique=True, verbose_name="Descrição"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
            ],
            options={
                "verbose_name": "Observação de etiqueta",
                "verbose_name_plural": "Observações de etiqueta",
                "db_table": 'qualidade"."observacao_etiqueta',
                "ordering": ["descricao"],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Reuniao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("data_hora_inicio", models.DateTimeField(verbose_name="Data e hora início")),
                (
                    "data_hora_fim",
                    models.DateTimeField(blank=True, null=True, verbose_name="Data e hora fim"),
                ),
            ],
            options={
                "verbose_name": "Reunião",
                "verbose_name_plural": "Reuniões",
                "db_table": 'qualidade"."reuniao',
                "ordering": ["-data_hora_inicio"],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="LiberacaoLote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("codemp", models.IntegerField(default=0, verbose_name="Empresa")),
                (
                    "numbob",
                    models.IntegerField(blank=True, null=True, verbose_name="Número da bobina"),
                ),
                ("codpro", models.CharField(max_length=50, verbose_name="Produto")),
                ("codder", models.CharField(max_length=20, verbose_name="Derivação")),
                ("coddep", models.CharField(max_length=20, verbose_name="Depósito")),
                (
                    "deptrf",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="Depósito transferido"
                    ),
                ),
                (
                    "codtns",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="Transação ERP"
                    ),
                ),
                (
                    "codigo_integrador",
                    models.CharField(max_length=50, verbose_name="Código Integrador"),
                ),
                ("codlot", models.CharField(max_length=50, verbose_name="Lote")),
                (
                    "lottrf",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="Lote transferido"
                    ),
                ),
                (
                    "codori",
                    models.CharField(blank=True, default="", max_length=20, verbose_name="Origem"),
                ),
                (
                    "numorp",
                    models.IntegerField(blank=True, null=True, verbose_name="Ordem de produção"),
                ),
                ("qtdtot", models.FloatField(verbose_name="Quantidade total")),
                ("qtdlibe", models.FloatField(default=0, verbose_name="Quantidade liberada")),
                ("qtdaverm", models.FloatField(default=0, verbose_name="Quantidade área vermelha")),
                ("qtdrefu", models.FloatField(default=0, verbose_name="Quantidade refugada")),
                ("qtdrecl", models.FloatField(default=0, verbose_name="Quantidade reclassificada")),
                (
                    "codpro_recl",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="Produto reclassificado"
                    ),
                ),
                (
                    "codder_recl",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="Derivação reclassificada",
                    ),
                ),
                (
                    "coddft",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="Código do motivo"
                    ),
                ),
                (
                    "observacao_geral",
                    models.TextField(blank=True, default="", verbose_name="Observação geral"),
                ),
                ("log", models.TextField(blank=True, default="", verbose_name="Log")),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "Não integrado"), (1, "Integrado"), (2, "Processando")],
                        default=0,
                        verbose_name="Status",
                    ),
                ),
                (
                    "datager",
                    models.DateTimeField(blank=True, null=True, verbose_name="Data e hora geração"),
                ),
                ("data_hora", models.DateTimeField(auto_now_add=True, verbose_name="Data e hora")),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="liberacoes_lote_qualidade",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
                (
                    "etiqueta",
                    models.ForeignKey(
                        blank=True,
                        db_column="id_etiqueta",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="liberacoes_lote",
                        to="qualidade.observacaoetiqueta",
                        verbose_name="Observação etiqueta",
                    ),
                ),
                (
                    "reuniao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="liberacoes_lote",
                        to="qualidade.reuniao",
                        verbose_name="Reunião",
                    ),
                ),
            ],
            options={
                "verbose_name": "Liberação de lote",
                "verbose_name_plural": "Liberações de lote",
                "db_table": 'qualidade"."liberacao_lote',
                "ordering": ["-data_hora"],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="ReuniaoParticipante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nome", models.CharField(max_length=150, verbose_name="Nome")),
                (
                    "setor",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("conversao", "Conversão"),
                            ("industrial", "Industrial"),
                            ("qualidade", "Qualidade"),
                            ("logistica", "Logística"),
                            ("pcp", "PCP"),
                        ],
                        default="",
                        max_length=20,
                        verbose_name="Setor",
                    ),
                ),
                (
                    "reuniao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participantes",
                        to="qualidade.reuniao",
                        verbose_name="Reunião",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participante da reunião",
                "verbose_name_plural": "Participantes da reunião",
                "db_table": 'qualidade"."reuniao_participantes',
                "ordering": ["nome"],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="WMS_IntegraçãoOP",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("codemp", models.IntegerField(verbose_name="Código da Empresa")),
                ("origem", models.CharField(max_length=10, verbose_name="Origem")),
                ("op", models.IntegerField(verbose_name="Ordem de Produção")),
                ("lote", models.CharField(default="0", max_length=50, verbose_name="Lote")),
                (
                    "palete",
                    models.CharField(blank=True, max_length=50, null=True, verbose_name="Palete"),
                ),
                (
                    "quantidade",
                    models.DecimalField(decimal_places=4, max_digits=12, verbose_name="Quantidade"),
                ),
                (
                    "codigo_integrador",
                    models.CharField(max_length=50, verbose_name="Código Integrador"),
                ),
                (
                    "local",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Local WMS"
                    ),
                ),
                (
                    "codpro",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Código do Produto"
                    ),
                ),
                ("codder", models.IntegerField(blank=True, null=True, verbose_name="Derivação")),
                ("log", models.TextField(blank=True, null=True, verbose_name="Log")),
                ("status", models.IntegerField(default=0, verbose_name="Status")),
                (
                    "tipo_envio",
                    models.CharField(
                        choices=[("novo_lote", "Novo lote"), ("ajuste", "Ajuste")],
                        default="novo_lote",
                        max_length=20,
                        verbose_name="Tipo de envio WMS",
                    ),
                ),
                ("data_hora", models.DateTimeField(auto_now=True, verbose_name="Data/Hora Log")),
                (
                    "reuniao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="integracoes_wms",
                        to="qualidade.reuniao",
                        verbose_name="Reunião",
                    ),
                ),
            ],
            options={
                "verbose_name": "Integração WMS OP",
                "verbose_name_plural": "Integrações WMS OP",
                "db_table": 'qualidade"."wms_integracao_op',
                "default_permissions": (),
            },
        ),
    ]
