# Generated by Django 6.0.5 on 2026-07-15 18:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qualidade", "0002_atualizar_permissoes_liberacao_lotes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="liberacaolote",
            index=models.Index(
                fields=["codemp", "numbob", "codlot", "codpro", "codder", "-id"],
                name="idx_lote_grupo_id",
            ),
        ),
        migrations.AddIndex(
            model_name="liberacaolote",
            index=models.Index(fields=["status", "-id"], name="idx_lote_status_id"),
        ),
    ]
