# Generated by Django 6.0.5 on 2026-07-15 18:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("qualidade", "0003_liberacaolote_idx_lote_grupo_id_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="liberacaolote",
            name="idx_lote_status_id",
        ),
    ]
