# Generated by Django 6.0.5 on 2026-07-15 18:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qualidade", "0004_remove_liberacaolote_idx_lote_status_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="liberacaolote",
            index=models.Index(fields=["status", "-id"], name="idx_lote_status_id"),
        ),
    ]
