# Generated by Django 6.0.5 on 2026-08-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qualidade", "0005_liberacaolote_idx_lote_status_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="liberacaolote",
            name="qtdprensa",
            field=models.FloatField(default=0, verbose_name="Quantidade para prensa"),
        ),
        migrations.AlterField(
            model_name="liberacaolote",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Não integrado"),
                    (1, "Integrado"),
                    (2, "Processando"),
                    (3, "Local (sem integração)"),
                ],
                default=0,
                verbose_name="Status",
            ),
        ),
    ]
