# Generated by Django 6.0.5 on 2026-08-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qualidade", "0008_normalizar_campos_texto_wms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wms_integraçãoop",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Não integrado"), (1, "Integrado"), (2, "Processando")],
                default=0,
                verbose_name="Status",
            ),
        ),
    ]
