# Generated by Django 6.0.5 on 2026-08-27 03:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("qualidade", "0011_alter_permissoesqualidade_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="permissoesqualidade",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": [
                    ("pode_acessar_liberacao_lotes", "Pode acessar a tela de liberação de lotes"),
                    ("pode_destinar_lotes_liberacao", "Pode destinar lotes na tela de liberação"),
                    (
                        "pode_acessar_area_vermelha",
                        "Pode acessar a tela de liberação da área vermelha",
                    ),
                    ("pode_destinar_area_vermelha", "Pode destinar lotes na área vermelha"),
                    (
                        "pode_cadastrar_observacoes_etiqueta",
                        "Pode cadastrar observações de etiqueta",
                    ),
                ],
            },
        ),
    ]
