# Generated by Django 6.0.5 on 2026-08-29 01:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qualidade", "0013_remove_permissao_excluir_integracao_wms"),
    ]

    operations = [
        migrations.AddField(
            model_name="wms_integraçãoop",
            name="datger",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Data/Hora Geração"),
        ),
    ]
